FROM nginx:stable-alpine
LABEL org.opencontainers.image.source="https://github.com/Johnthunderr/course-app"
LABEL org.opencontainers.image.description="Lab 1 static page by Janis Irbe"
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80